version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_volunteer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: volunteer_platform
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s
    command: ["mysqld", "--bind-address=0.0.0.0"]

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: volunteer_server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/volunteer_platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: volunteer_client
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
